### ISSUE TITLE
Linux Installation Guide

### ISSUE THREAD

**Issue by neoabs** [Argent77/PST-UB-reloaded#1]
I have tried installing mod under linux (manjaro) for steam version of game but got error instead:

```
[admin@Adimn Project P]$ weidu setup-PST-UB-reloaded.tp2
[weidu] WeiDU version 24600
[./chitin.key] 249 BIFFs, 14569 resources

ERROR: Unable to find DIALOG.TLK in:
	./^dialog/.tlk$

Please run this program in your Infinity Engine game directory.
```
I have no prior experience with moding Infinity Engine games and readme is for Windows version only. 

Please help

**Comment by Argent77** [comment]
Afaik, you'll need to prepare either the game or the folder/partition where the game is installed to properly deal with case-sensitive filenames. There is a [Linux Guide](https://www.gibberlings3.net/forums/topic/28516-the-linux-users-guide-to-installing-mods-on-the-enhanced-editions/) at G3 Forums which provides a couple of potential solutions.
