### ISSUE TITLE
Untranslated 57437 ~Kemak~

### ISSUE THREAD

**Issue by EugVV** [Argent77/PST-UB-reloaded#11]
CurstPrisoners.tph contains this code:

```
STRING_SET 57437 ~Kemak~
COPY_EXISTING ~KENAK.CRE~ ~override/KEMAK.CRE~
  WRITE_LONG 0x8 57437 // Kemak
  WRITE_LONG 0xc 57437 // Kemak
 BUT_ONLY
```

So I have an untranslated name for this character with a Russian translation.

**Comment by Argent77** [comment]
Good catch. This appears to be an issue inherited from the original PST-UB. Will be fixed.
