### ISSUE TITLE
Make antimagic spell effect messages translatable

### ISSUE THREAD

**Issue by EugVV** [Argent77/PST-UB-reloaded#13]
For now, the messages about antimagic spell effects are hard-coded in the file SpellKeys/tph/SpellKeys.tph, they are "Spell Failure" and "Remove Spell Failure".
I think it would be good to provide a possibility to translate them.
As a Russian translation I can suggest "Провал заклинаний" and "Устранение провала заклинаний".

**Comment by Argent77** [comment]
These spells are silently applied to the target via script without printing any feedback messages to the log window. I don't think a translation is needed. But I can traify them anyway if you think that it will help modders or players when using a savegame or resource editor.

**Comment by EugVV** [comment]
![Spell_Failure_Effect](https://github.com/user-attachments/assets/85cbfaa3-6fb3-4d0a-b55c-41124df8783e)

**Comment by Argent77** [comment]
Good point. Spells will be traified.

**Comment by Argent77** [comment]
Fixed by 0d6b796b874947ece556d5d92fcb367b109a5f0e
